CREATE TABLE user_profiles(
	profile_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id number NOT NULL,
	baseline_vector varchar(500) NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

INSERT INTO user_profile (user_id,baseline_vector)
VALUES ("125695","100,105,110,108")

COMMIT

MERGE INTO user_profiles p
USING (SELECT 1 AS u_id, '120,150,180'  AS vec FROM dual) s
ON (p.user_id = s.u_id)
WHEN MATCHED THEN
  UPDATE SET p.baseline_vector = s.vec
WHEN NOT MATCHED THEN
  INSERT (user_id, baseline_vector) VALUES (s.u_id, s.vec);

ALTER TABLE "USER_PROFILES" ADD "FAILED_ATTEMPTS" NUMBER DEFAULT 0;
COMMIT;

UPDATE "USER_PROFILES" SET "FAILED_ATTEMPTS" = 0 WHERE "USER_ID" = 1;
COMMIT;